name: Twinkies
version: '${project.version}'
main: me.wyne.twinkies.Twinkies
api-version: 1.19
depend: [ PlaceholderAPI ]
author: Wyne
website: https://github.com/Wyne10
commands:
  twinkies:
permissions:
  twinkies.*:
    default: op
  twinkies.notifications:
    description: Allows player to receive notifications
  twinkies.playerData:
    description: Allows player to read and modify saved player data
  twinkies.logging:
    description: Allows player to set logging settings
