# Настройки уведомлений приходящих администраторам

# Вход нового игрока
notif-register: "<green>Зарегистрирован новый игрок
             <br>Никнейм: %player_name%
             <br>IP: %player_ip%"

# Вход игрока
notif-join: "<blue>Игрок '%player_name%' вошёл на сервер с IP '%player_ip%'"

# Вход со сменённым никнеймом
notif-change-nick: "<red>Игрок '%player_name%' вошёл на сервер с изменённым никнеймом
                   <br>Прошлый никнейм: '%twinkies_last_nick%'"

# Вход с новым никнеймом
notif-new-nick: "<red>Игрок '%player_name%' вошёл на сервер с новым никнеймом
                <br>Прошлый никнейм: '%twinkies_last_nick%'"

# Вход с дублирующегося никнейма
notif-dupe-nick: "<red>Игрок '%player_name%' вошёл на сервер с дублирующегося никнейма
               <br>Этот никнейм уже был замечен у игрока '%player_dupe%'"

# Вход со сменённым IP
notif-change-ip: "<red>Игрок '%player_name%' вошёл на сервер с изменённым IP адресом: '%player_ip%'
                 <br>Прошлый IP: '%twinkies_last_ip%'"

# Вход с нового IP
notif-new-ip: "<red>Игрок '%player_name%' вошёл на сервер с нового IP адреса: '%player_ip%'
              <br>Прошлый IP: '%twinkies_last_ip%'"

# Вход с дублирующегося IP
notif-dupe-ip: "<red>Игрок '%player_name%' вошёл на сервер с дублирующегося IP адреса: '%player_ip%'
               <br>Этот IP уже был замечен у игрока '%player_dupe%'"

# Настройки логирования

# Логирование ошибок
log-err: true
# Логирование предупреждений
log-warn: true
# Логирование информации
log-info: true
# Логирование запросов json
log-jsonQuery: false
# Логирование входа нового игрока
log-register: true
# Логирование входа игрока
log-join: true
# Логирование смены ника игрока
log-change-nick: true
# Логирование нового ника игрока
log-new-nick: true
# Логирование дублирующегося никнейма игрока
log-dupe-nick: true
# Логирование смены IP игрока
log-change-ip: true
# Логирование нового IP игрока
log-new-ip: true
# Логирование дублирующегося IP игрока
log-dupe-ip: true